"""
Utility modules for model-generator.
"""

from .loaders import (
    deep_merge,
    get_layout,
    load_config,
    load_model,
    load_shared_constraints,
    load_shared_enums,
)
from .parser import scan_api_model_files, scan_model_files
from .quality import run_quality_tools
from .templates import get_template_env, path_to_import

# Generated file marker - consistent across all generated files
GENERATED_MARKER = "# THIS CODE WAS INITIALLY GENERATED BY model-generator"

__all__ = [
    "GENERATED_MARKER",
    "deep_merge",
    "get_layout",
    "get_template_env",
    "load_config",
    "load_model",
    "load_shared_constraints",
    "load_shared_enums",
    "path_to_import",
    "run_quality_tools",
    "scan_api_model_files",
    "scan_model_files",
]
