"""
Migration generation utilities (Alembic).
"""

from pathlib import Path
from typing import Any

from jinja2 import Environment

# Canonical list of custom SQLAlchemy type class names emitted by types.py.j2.
# This is the single source of truth — env.py.j2 reads this via the template
# variable ``custom_type_names`` rather than hardcoding the names.
_CUSTOM_TYPE_NAMES: tuple[str, ...] = ("PortableNumeric", "PortableUuid")


def generate_migration_init(
    model: dict[str, Any],
    config: dict[str, Any],
    env: Environment,
    project_root: Path,
    no_root_files: bool = False,
    dry_run: bool = False,
    diff: bool = False,
) -> list[dict[str, Any]]:
    """Initialize Alembic migration structure.

    When ``no_root_files`` is set, the project-root ``alembic.ini`` is
    suppressed while the in-tree alembic/ scaffolding (env.py,
    script.py.mako, README, versions/.gitkeep) still emits — those live
    inside the migrations directory, not at the project root.
    """
    outputs = []

    migrations_dir = project_root / config["paths"].get("migrations", "alembic")
    versions_dir = migrations_dir / "versions"

    if not dry_run and not diff:
        migrations_dir.mkdir(parents=True, exist_ok=True)
        versions_dir.mkdir(parents=True, exist_ok=True)

    # alembic.ini (bootstrap-only; don't overwrite adopter customizations)
    if not no_root_files:
        alembic_ini_path = project_root / "alembic.ini"
        if not alembic_ini_path.exists():
            template = env.get_template("migrations/ini.j2")
            content = template.render(config=config)
            outputs.append({"path": alembic_ini_path, "content": content})

    # env.py
    template = env.get_template("migrations/env.py.j2")
    content = template.render(config=config, custom_type_names=_CUSTOM_TYPE_NAMES)
    outputs.append({"path": migrations_dir / "env.py", "content": content})

    # script.py.mako
    template = env.get_template("migrations/script.py.mako.j2")
    content = template.render(config=config)
    outputs.append({"path": migrations_dir / "script.py.mako", "content": content})

    # README.md
    outputs.append(
        {
            "path": migrations_dir / "README.md",
            "content": _get_migration_readme(),
        }
    )

    # .gitkeep
    outputs.append({"path": versions_dir / ".gitkeep", "content": ""})

    return outputs


def _get_migration_readme() -> str:
    """Return README content for migrations directory."""
    return """# Database Migrations

This directory contains database migration files managed by Alembic.

## Usage

### Create a new migration
```bash
alembic revision --autogenerate -m "description of changes"
```

### Apply migrations
```bash
alembic upgrade head
```

### Rollback migrations
```bash
alembic downgrade -1
```

### View migration history
```bash
alembic history
```

### View current revision
```bash
alembic current
```

## Environment Variables

Set `DATABASE_URL` environment variable before running migrations:
```bash
export DATABASE_URL="postgresql://user:pass@localhost/dbname"
alembic upgrade head
```

## Generated by model-generator
"""


# Project-agnostic guidance: autogeneration needs a live database, so it can't
# run during generation. Kept free of any specific database/orchestration tool
# (no TimescaleDB/docker-compose) per the project-agnostic principle.
_AUTOGEN_INSTRUCTIONS = """
📋 Migration autogeneration requires a running database.

   model-generator has created your SQLAlchemy models — to create the
   corresponding Alembic migration, run these commands from your project root:

   1. Start your database and make sure it is reachable.

   2. Point Alembic at it and generate the migration:
      export DATABASE_URL="postgresql+asyncpg://user:pass@localhost:5432/dbname"
      alembic revision --autogenerate -m "initial schema"

   3. Apply it:
      alembic upgrade head
"""


def generate_migration_autogen(
    model: dict[str, Any], config: dict[str, Any], env: Environment, project_root: Path
) -> None:
    """
    Print instructions for running Alembic autogenerate; emit no files.

    Autogeneration can't run during generation — it requires a live database
    (DATABASE_URL). This target only surfaces guidance, so it returns ``None``
    (rather than a sentinel dict the output dispatch had to special-case).
    """
    alembic_ini = project_root / "alembic.ini"

    if not alembic_ini.exists():
        print("  ⚠️  Alembic not initialized. Run with --target migration-init first.")
        return None

    print(_AUTOGEN_INSTRUCTIONS)
    return None
