"""
Migration generation utilities (Alembic).
"""

from pathlib import Path
from typing import Any

from jinja2 import Environment


def generate_migration_init(
    model: dict[str, Any],
    config: dict[str, Any],
    env: Environment,
    project_root: Path,
    no_root_files: bool = False,
) -> list[dict[str, Any]]:
    """Initialize Alembic migration structure.

    When ``no_root_files`` is set, the project-root ``alembic.ini`` is
    suppressed while the in-tree alembic/ scaffolding (env.py,
    script.py.mako, README, versions/.gitkeep) still emits — those live
    inside the migrations directory, not at the project root.
    """
    outputs = []

    migrations_dir = project_root / config["paths"].get("migrations", "alembic")
    versions_dir = migrations_dir / "versions"

    migrations_dir.mkdir(parents=True, exist_ok=True)
    versions_dir.mkdir(parents=True, exist_ok=True)

    # alembic.ini (bootstrap-only; don't overwrite adopter customizations)
    if not no_root_files:
        alembic_ini_path = project_root / "alembic.ini"
        if not alembic_ini_path.exists():
            template = env.get_template("migrations/ini.j2")
            content = template.render(config=config)
            outputs.append({"path": alembic_ini_path, "content": content})

    # env.py
    template = env.get_template("migrations/env.py.j2")
    content = template.render(config=config)
    outputs.append({"path": migrations_dir / "env.py", "content": content})

    # script.py.mako
    template = env.get_template("migrations/script.py.mako.j2")
    content = template.render(config=config)
    outputs.append({"path": migrations_dir / "script.py.mako", "content": content})

    # README.md
    outputs.append(
        {
            "path": migrations_dir / "README.md",
            "content": _get_migration_readme(),
        }
    )

    # .gitkeep
    outputs.append({"path": versions_dir / ".gitkeep", "content": ""})

    return outputs


def _get_migration_readme() -> str:
    """Return README content for migrations directory."""
    return """# Database Migrations

This directory contains database migration files managed by Alembic.

## Usage

### Create a new migration
```bash
alembic revision --autogenerate -m "description of changes"
```

### Apply migrations
```bash
alembic upgrade head
```

### Rollback migrations
```bash
alembic downgrade -1
```

### View migration history
```bash
alembic history
```

### View current revision
```bash
alembic current
```

## Environment Variables

Set `DATABASE_URL` environment variable before running migrations:
```bash
export DATABASE_URL="postgresql://user:pass@localhost/dbname"
alembic upgrade head
```

## Generated by model-generator
"""


def generate_migration_autogen(
    model: dict[str, Any], config: dict[str, Any], env: Environment, project_root: Path
) -> dict[str, Any] | None:
    """
    Return instructions for running Alembic autogenerate.

    This can't be run directly during generation as it requires DATABASE_URL.
    """
    alembic_ini = project_root / "alembic.ini"

    if not alembic_ini.exists():
        print("  ⚠️  Alembic not initialized. Run with --target migration-init first.")
        return None

    print("  Running alembic revision --autogenerate...")

    return {
        "info": (
            "Migration autogeneration requires DATABASE_URL and should be run manually"
        ),
        "instructions": """
📋 Migration autogeneration requires a running database.

   Model-generator has created your SQLAlchemy models — to create the
   corresponding Alembic migration, run these commands from your project root:

   1. Start your database (if not already running):
      docker-compose up -d timescaledb   # or: docker-compose up -d postgres

   2. Generate the migration:
      export DATABASE_URL="postgresql://user:pass@localhost:5432/dbname"
      alembic revision --autogenerate -m "initial schema"

   3. Apply it:
      alembic upgrade head
""",
    }
